# Generated by Django 3.0.8 on 2020-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200806_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_image', models.ImageField(upload_to='')),
                ('probability', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patient',
            field=models.ManyToManyField(to='app.Patient'),
        ),
    ]
