# Generated by Django 3.0.8 on 2020-08-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200806_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
