# Generated by Django 3.0.8 on 2020-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_patient_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
