# Generated by Django 3.0.8 on 2020-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200806_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
