# Generated by Django 3.0.8 on 2020-08-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_doctor_tlf'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='grade',
            field=models.CharField(blank=True, choices=[(None, 'Votre grade'), ('Résident', 'Résident'), ('Assistant', 'Assistant'), ('Maitre assistant', 'Maitre assistant'), ('Maitre de conference A', 'Maitre de conference A'), ('Maitre de conference B', 'Maitre de conference B'), ('Professeur', 'Professeur')], max_length=200, null=True, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialite',
            field=models.CharField(blank=True, choices=[(None, 'Votre specialité'), ('Ophtalmologie', 'Ophtalmologie'), ('Radiologie', 'Radiologie'), ('ORL', 'ORL'), ('Cardiologie', 'Cardiologie'), ('Pneumologie', 'Pneumologie'), ('Neurologie', 'Neurologie'), ('Rhumatologie', 'Rhumatologie'), ('Infectiologie', 'Infectiologie'), ('Hématologie', 'Hématologie'), ('Gasto-entéro-hépatologie', 'Gasto-entéro-hépatologie'), ('Dermatologie', 'Dermatologie')], max_length=200, null=True, verbose_name='specialite'),
        ),
    ]
