# Generated by Django 3.0.8 on 2020-08-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
