# Generated by Django 3.0.8 on 2020-09-17 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200917_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
